<a href="https://colab.research.google.com/github/RoyArkh/MLbasics/blob/main/pytorch_00_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)


# practicing from readings

import torch

tensorB = torch.BoolTensor(3, 2)
tensorB

tensor([[True, True],
        [True, True],
        [True, True]])

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor

randtensor2 = torch.rand(7, 7)

randtensor2

tensor([[0.7941, 0.5636, 0.7253, 0.5136, 0.8700, 0.5346, 0.9016],
        [0.0536, 0.6030, 0.9894, 0.4399, 0.3880, 0.3703, 0.2665],
        [0.1377, 0.2288, 0.2827, 0.2295, 0.8783, 0.6866, 0.4530],
        [0.1709, 0.0564, 0.3879, 0.7947, 0.8828, 0.0456, 0.7257],
        [0.4540, 0.4547, 0.7280, 0.6603, 0.8531, 0.8163, 0.3384],
        [0.2220, 0.4393, 0.5993, 0.1628, 0.2376, 0.0460, 0.5905],
        [0.1009, 0.2307, 0.0626, 0.6474, 0.1625, 0.4883, 0.4845]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
from ast import MatMult
# Create another random tensor

randtensor3 = torch.rand(1, 7)

# Perform matrix multiplication

torch.matmul(randtensor2, randtensor3.T)

tensor([[2.0997],
        [1.3469],
        [1.5570],
        [1.2238],
        [1.9801],
        [0.9231],
        [1.1419]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
tensor40 = torch.rand(7, 7)

# torch.manual_seed(RANDOM_SEED) --> somehow there's no need to mention this twice
tensor41 = torch.rand(1, 7)

# Matrix multiply tensors

torch.matmul(tensor40, tensor41.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU

torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
RANDOM_SEED = 1234

# Check for access to GPU
mydevice = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
torch.manual_seed(RANDOM_SEED)

# tensor60 = torch.rand(2, 3, device=mydevice)
# tensor61 = torch.rand(2, 3, device=mydevice)

tensor60 = torch.rand(2, 3).to(mydevice)
tensor61 = torch.rand(2, 3).to(mydevice)

print(mydevice)
tensor60, tensor61

cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
multensor = torch.matmul(tensor60, tensor61.T)
multensor, multensor.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max = multensor.max()

# Find min
min = multensor.min()

max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
max_indx = torch.argmax(multensor)

# Find arg min
min_indx = torch.argmin(multensor)

max_indx, min_indx

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
RANDOM_SEED = 7

# Create random tensor
rand10 = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
rand10 = rand10.squeeze()

# Print out tensors and their shapes
rand10, rand10.shape

(tensor([0.7893, 0.3216, 0.5247, 0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108,
         0.0014]),
 torch.Size([10]))