In [ ]:
import torch
print(torch.__version__)

2.1.0+cu118


# *1. Starting off with scalars*

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim #dimension of the tensor

0

In [ ]:
scalar.item() #returns a python integer

7

# *2. The vectors*

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim #usually the dimension can be calculated by the number of square brackets

1

In [ ]:
vector.shape

torch.Size([2])

# *3. The Matrices*

In [ ]:
MATRIX = torch.tensor([[7, 7],
                      [5, 5]])
MATRIX

tensor([[7, 7],
        [5, 5]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]
MATRIX[1]

tensor([5, 5])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

# *4. TENSORS*

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR[0, 1]

tensor([4, 5, 6])

In [ ]:
TENSOR[0, 2, 2]

tensor(9)

The reason for the shape being (1, 3, 3) is that within the tensor we have one element, which consists of 3 sub-elements, each of those have 3 items in them

# *5. Random Tensors*

In [ ]:
rnd_tensor = torch.rand(3, 4)
rnd_tensor

tensor([[0.3381, 0.8192, 0.3611, 0.4290],
        [0.7652, 0.0044, 0.7277, 0.7201],
        [0.6178, 0.2819, 0.3163, 0.2059]])

In [ ]:
rnd_tensor.ndim

2

In [ ]:
rnd_tensor_2 = torch.rand(2, 5, 2)
rnd_tensor_2

tensor([[[0.1543, 0.2758],
         [0.9586, 0.4213],
         [0.3504, 0.0368],
         [0.9719, 0.6650],
         [0.9683, 0.1370]],

        [[0.8299, 0.3945],
         [0.0151, 0.0064],
         [0.9175, 0.8607],
         [0.8479, 0.5419],
         [0.2224, 0.8708]]])

In [ ]:
rnd_tensor_2.ndim

3

In [ ]:
#somthing like tensor for images

rnd_imagesize_tensor = torch.rand(255, 255, 3) #height, width, colour channels
rnd_imagesize_tensor

tensor([[[0.4890, 0.6618, 0.2619],
         [0.9808, 0.7717, 0.3934],
         [0.4579, 0.4518, 0.5585],
         ...,
         [0.1473, 0.1044, 0.4672],
         [0.3442, 0.8875, 0.4997],
         [0.5369, 0.3665, 0.7762]],

        [[0.4023, 0.6059, 0.9407],
         [0.2054, 0.0813, 0.4582],
         [0.0096, 0.9701, 0.3688],
         ...,
         [0.0934, 0.0210, 0.6346],
         [0.5888, 0.3045, 0.1971],
         [0.4094, 0.9787, 0.7666]],

        [[0.7981, 0.4950, 0.2464],
         [0.1050, 0.7004, 0.7140],
         [0.7110, 0.1489, 0.2729],
         ...,
         [0.9536, 0.3771, 0.6982],
         [0.4700, 0.2701, 0.3958],
         [0.6522, 0.0663, 0.2053]],

        ...,

        [[0.8802, 0.3709, 0.1578],
         [0.3231, 0.7390, 0.4729],
         [0.7943, 0.6878, 0.7152],
         ...,
         [0.6898, 0.6001, 0.6219],
         [0.7703, 0.6361, 0.8335],
         [0.0399, 0.8447, 0.5854]],

        [[0.1843, 0.6301, 0.0258],
         [0.9846, 0.5250, 0.5505],
         [0.

In [ ]:
rnd_imagesize_tensor.shape, rnd_imagesize_tensor.ndim

(torch.Size([255, 255, 3]), 3)

# *6. Zeroes and Ones*

In [ ]:
zero_tensor = torch.zeros(3, 2, 3, 4)
zero_tensor

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])

In [ ]:
one_tensor = torch.ones(2, 5)
one_tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
one_tensor.dtype #shows the type of the element; usually it is the standart -> a float32 -> 32 bit float

torch.float32

# *7. Range and tensors-like*

In [ ]:
one_to_ten = torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
range_w_skips = torch.arange(start=0, end=51, step=5)
range_w_skips

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
#creating tensors with shapes like the given ones

ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# *8. Datatypes*

3 most common errors arise from here:
1. Tensor has wrong data type
2. Tensor has wrong shape
3. Tensor is not on the write devise

In [ ]:
#default -> float 32
f32_tensor = torch.tensor([3.0, 4.0, 5.0],
                          dtype = None, #what datatype the tensor is gonna use, even if u put none it will default to float32
                          device = None, #the device that the tensor is on (cpu, gpu[cuda], tpu, etc.)
                          requires_grad = False) #whether to track the gradient of the tensor in calculations
f32_tensor

tensor([3., 4., 5.])

In [ ]:
f32_tensor.dtype

torch.float32

In [ ]:
f16_tensor = f32_tensor.type(torch.half) #new tensor with info from last tensor but shortened
f16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [ ]:
f16_tensor.dtype

torch.float16

with usual tensors:

default -> f32

half -> f16

double -> f64
_____

there are also complex, bit integer(signed/unsigned), bools, and quantized tensors
(https://pytorch.org/docs/stable/tensors.html)

In [ ]:
fidk_tensor = f32_tensor * f16_tensor
fidk_tensor.dtype

torch.float32

In [ ]:
int32_tensor = torch.tensor([3.9999999, 4, 5],
                            dtype = torch.int32)
#ig it uses floor function (or basically taakes only the full integer side) to put the float to int
int32_tensor

tensor([3, 4, 5], dtype=torch.int32)

In [ ]:
some_rnd_tensor = torch.rand(3, 4,
                             dtype = None,
                             device = 'cpu',)

some_rnd_tensor, some_rnd_tensor.dtype, some_rnd_tensor.device

(tensor([[0.8515, 0.6261, 0.8428, 0.5843],
         [0.0861, 0.1090, 0.8824, 0.7022],
         [0.7831, 0.7251, 0.5584, 0.7187]]),
 torch.float32,
 device(type='cpu'))

In [ ]:
some_rnd_tensor.to(device="cpu") #this is changing the location devide but since I don't have cuda(gpu) or anything else linked I still wrote cpu
some_rnd_tensor.device

device(type='cpu')

# *9. Tensor maths*

+, -, /, scalar *, matrix *

In [ ]:
plus_tensor = torch.tensor([[1, 2, 3],[4, 5, 6]])
one_plus_tensor = torch.ones_like(plus_tensor)
one_plus_tensor + plus_tensor

tensor([[2, 3, 4],
        [5, 6, 7]])

In [ ]:
minus_tensor = torch.rand(2, 3, 1)
minus_tensor

tensor([[[0.0022],
         [0.5229],
         [0.9980]],

        [[0.1140],
         [0.9251],
         [0.2779]]])

In [ ]:
minus_tensor2 = torch.rand_like(minus_tensor)
minus_tensor2

tensor([[[0.6229],
         [0.0585],
         [0.5972]],

        [[0.1400],
         [0.6545],
         [0.3728]]])

In [ ]:
minus_tensor - minus_tensor2

tensor([[[-0.6207],
         [ 0.4644],
         [ 0.4008]],

        [[-0.0260],
         [ 0.2706],
         [-0.0950]]])

In [ ]:
scalarmult_tensor = torch.randint(10, (2, 4))
scalarmult_tensor

tensor([[5, 2, 8, 4],
        [7, 9, 0, 7]])

In [ ]:
scalarmult_tensor * 2

tensor([[10,  4, 16,  8],
        [14, 18,  0, 14]])

In [ ]:
division = scalarmult_tensor / 2

In [ ]:
scalarmult_tensor.dtype, division.dtype

(torch.int64, torch.float32)

In [ ]:
multmatrix_tensor = torch.randint(6, (3, 3))
multmatrix_tensor

tensor([[0, 3, 0],
        [2, 0, 2],
        [2, 1, 1]])

In [ ]:
multmatrix_tensor * 10

tensor([[ 0, 30,  0],
        [20,  0, 20],
        [20, 10, 10]])

In [ ]:
multmatrix_tensor2 = torch.randint_like(multmatrix_tensor, 6)
multmatrix_tensor2

tensor([[3, 3, 5],
        [3, 3, 4],
        [3, 1, 5]])

In [ ]:
matproduct = multmatrix_tensor * multmatrix_tensor2
matproduct #this is the element-wise multiplication of two matrices

tensor([[0, 9, 0],
        [6, 0, 8],
        [6, 1, 5]])

In [ ]:
matdotproduct = torch.matmul(multmatrix_tensor, multmatrix_tensor2)
matdotproduct

tensor([[ 9,  9, 12],
        [12,  8, 20],
        [12, 10, 19]])

In [ ]:
multmat_notsame = torch.tensor([2, 5, 4])
multmat_notsame

tensor([2, 5, 4])

In [ ]:
torch.matmul(multmat_notsame, multmat_notsame)

tensor(45)

In [ ]:
#matproduct is a 3x3 matrix
twobytwo = torch.randint(1, 4, (2, 2))
twobytwo

tensor([[1, 3],
        [3, 1]])

In [ ]:
#torch.matmul(twobytwo, matproduct) #results in the expected error of the wrong sizes

In [ ]:
threebytwo = torch.randint(6, (3, 2))
threebytwo

tensor([[5, 5],
        [0, 0],
        [1, 1]])

In [ ]:
#torch.matmul(twobytwo, threebytwo) --> will result in an error
#but we can use a transpose of threebytwo and make it 2x3 and then the inner dimensions will match

torch.matmul(twobytwo, threebytwo.T)

tensor([[20,  0,  4],
        [20,  0,  4]])

# *10. Tensor Aggregation (min, max, mean, sum, etc.)*

In [ ]:
testing_agg_tensor = torch.arange(5, 51, 5)
testing_agg_tensor

tensor([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
%%time
testing_agg_tensor.min()

CPU times: user 91 µs, sys: 0 ns, total: 91 µs
Wall time: 96.1 µs


tensor(5)

In [ ]:
%%time
torch.min(testing_agg_tensor)

CPU times: user 569 µs, sys: 35 µs, total: 604 µs
Wall time: 535 µs


tensor(5)

In [ ]:
testing_agg_tensor.max()

tensor(50)

In [ ]:
# testing_agg_tensor.mean() --> causes
#RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
testing_agg_tensor.type(torch.float16).mean()

tensor(27.5000, dtype=torch.float16)

In [ ]:
%%time
testing_agg_tensor.type(torch.float16).mean()

CPU times: user 149 µs, sys: 0 ns, total: 149 µs
Wall time: 154 µs


tensor(27.5000, dtype=torch.float16)

In [ ]:
%%time
testing_agg_tensor.type(torch.float32).mean()

CPU times: user 1.22 ms, sys: 0 ns, total: 1.22 ms
Wall time: 1.23 ms


tensor(27.5000)

In [ ]:
testing_agg_tensor.sum()

tensor(275)

In [ ]:
testing_agg_tensor.median()

tensor(25)

In [ ]:
testing_agg_tensor.argmin() #returns the position of the smallest element

tensor(0)

In [ ]:
testing_agg_tensor.argmax()

tensor(9)

# *11. Reshaping, Stacking, (Un)squeezing, Permute*

In [ ]:
import torch

test_11 = torch.arange(1, 20, 2);
test_11, test_11.shape

(tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]), torch.Size([10]))

In [ ]:
test_reshape = torch.reshape(test_11, [1, 10])
test_reshape

tensor([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])

In [ ]:
test_reshape = torch.reshape(test_11, [1, 1, 1, 10])
test_reshape

tensor([[[[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]]]])

In [ ]:
test_reshape = torch.reshape(test_11, [2, 5])
test_reshape

tensor([[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19]])

In [ ]:
test_reshape = torch.reshape(test_11, [10, 1])
test_reshape

tensor([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]])

In [ ]:
test_reshape = torch.reshape(test_11, [2, 1, 5])
test_reshape

tensor([[[ 1,  3,  5,  7,  9]],

        [[11, 13, 15, 17, 19]]])

In [ ]:
test_reshape = torch.reshape(test_11, [10, 1, 1])
test_reshape

tensor([[[ 1]],

        [[ 3]],

        [[ 5]],

        [[ 7]],

        [[ 9]],

        [[11]],

        [[13]],

        [[15]],

        [[17]],

        [[19]]])

In [ ]:
test_view = test_11.view(10, 1)
print(test_view, "\n", test_11)

tensor([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]]) 
 tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])


In [ ]:
test_view[0, 0] = 5
print(test_view, "\n", test_11)

tensor([[ 5],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]]) 
 tensor([ 5,  3,  5,  7,  9, 11, 13, 15, 17, 19])


In [ ]:
test_11[9] = 0
print(test_view, "\n", test_11)

tensor([[ 5],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [ 0]]) 
 tensor([ 5,  3,  5,  7,  9, 11, 13, 15, 17,  0])


In [ ]:
test_stack = torch.stack([test_11, test_11])
test_stack

tensor([[ 5,  3,  5,  7,  9, 11, 13, 15, 17,  0],
        [ 5,  3,  5,  7,  9, 11, 13, 15, 17,  0]])

In [ ]:
test_stack = torch.stack([test_11, test_11, test_11, test_11], dim=-0)
test_stack

tensor([[ 5,  3,  5,  7,  9, 11, 13, 15, 17,  0],
        [ 5,  3,  5,  7,  9, 11, 13, 15, 17,  0],
        [ 5,  3,  5,  7,  9, 11, 13, 15, 17,  0],
        [ 5,  3,  5,  7,  9, 11, 13, 15, 17,  0]])

In [ ]:
test_111 = torch.randint(5, (1, 2, 3))
test_111

tensor([[[2, 4, 4],
         [4, 0, 3]]])

In [ ]:
test_sqz = torch.squeeze(test_111)
test_sqz

tensor([[2, 4, 4],
        [4, 0, 3]])

In [ ]:
test_sqz.unsqueeze(dim=2)

tensor([[[2],
         [4],
         [4]],

        [[4],
         [0],
         [3]]])

In [ ]:
test_112_img = torch.rand(255, 255, 3)
test_112_img

tensor([[[0.2429, 0.2083, 0.0680],
         [0.1217, 0.5065, 0.5690],
         [0.6782, 0.3492, 0.4975],
         ...,
         [0.4060, 0.9644, 0.1535],
         [0.4760, 0.8624, 0.2107],
         [0.8566, 0.2702, 0.4636]],

        [[0.4791, 0.4142, 0.2625],
         [0.9282, 0.1774, 0.5177],
         [0.4504, 0.0120, 0.3353],
         ...,
         [0.1806, 0.1948, 0.7910],
         [0.8899, 0.1376, 0.0449],
         [0.6168, 0.3283, 0.2735]],

        [[0.6926, 0.9829, 0.9999],
         [0.8508, 0.4071, 0.2063],
         [0.5743, 0.9052, 0.8379],
         ...,
         [0.3455, 0.1806, 0.3412],
         [0.1473, 0.1248, 0.0824],
         [0.3675, 0.4803, 0.9717]],

        ...,

        [[0.6717, 0.2124, 0.9649],
         [0.4454, 0.8084, 0.0336],
         [0.1782, 0.6691, 0.6045],
         ...,
         [0.5583, 0.1123, 0.6382],
         [0.8951, 0.6208, 0.7568],
         [0.6013, 0.4189, 0.3824]],

        [[0.5329, 0.1500, 0.6710],
         [0.0660, 0.6279, 0.9239],
         [0.

In [ ]:
test_permute = test_112_img.permute(2, 0, 1)
test_permute

tensor([[[0.2429, 0.1217, 0.6782,  ..., 0.4060, 0.4760, 0.8566],
         [0.4791, 0.9282, 0.4504,  ..., 0.1806, 0.8899, 0.6168],
         [0.6926, 0.8508, 0.5743,  ..., 0.3455, 0.1473, 0.3675],
         ...,
         [0.6717, 0.4454, 0.1782,  ..., 0.5583, 0.8951, 0.6013],
         [0.5329, 0.0660, 0.3471,  ..., 0.6596, 0.9859, 0.1559],
         [0.1055, 0.3151, 0.0712,  ..., 0.4927, 0.8812, 0.3890]],

        [[0.2083, 0.5065, 0.3492,  ..., 0.9644, 0.8624, 0.2702],
         [0.4142, 0.1774, 0.0120,  ..., 0.1948, 0.1376, 0.3283],
         [0.9829, 0.4071, 0.9052,  ..., 0.1806, 0.1248, 0.4803],
         ...,
         [0.2124, 0.8084, 0.6691,  ..., 0.1123, 0.6208, 0.4189],
         [0.1500, 0.6279, 0.7025,  ..., 0.8771, 0.7571, 0.4509],
         [0.7046, 0.7035, 0.7733,  ..., 0.7053, 0.5162, 0.7221]],

        [[0.0680, 0.5690, 0.4975,  ..., 0.1535, 0.2107, 0.4636],
         [0.2625, 0.5177, 0.3353,  ..., 0.7910, 0.0449, 0.2735],
         [0.9999, 0.2063, 0.8379,  ..., 0.3412, 0.0824, 0.

In [ ]:
test_112_img[0, 0, 0] = 0.123
print(test_112_img, "\n", test_permute)

tensor([[[0.1230, 0.2083, 0.0680],
         [0.1217, 0.5065, 0.5690],
         [0.6782, 0.3492, 0.4975],
         ...,
         [0.4060, 0.9644, 0.1535],
         [0.4760, 0.8624, 0.2107],
         [0.8566, 0.2702, 0.4636]],

        [[0.4791, 0.4142, 0.2625],
         [0.9282, 0.1774, 0.5177],
         [0.4504, 0.0120, 0.3353],
         ...,
         [0.1806, 0.1948, 0.7910],
         [0.8899, 0.1376, 0.0449],
         [0.6168, 0.3283, 0.2735]],

        [[0.6926, 0.9829, 0.9999],
         [0.8508, 0.4071, 0.2063],
         [0.5743, 0.9052, 0.8379],
         ...,
         [0.3455, 0.1806, 0.3412],
         [0.1473, 0.1248, 0.0824],
         [0.3675, 0.4803, 0.9717]],

        ...,

        [[0.6717, 0.2124, 0.9649],
         [0.4454, 0.8084, 0.0336],
         [0.1782, 0.6691, 0.6045],
         ...,
         [0.5583, 0.1123, 0.6382],
         [0.8951, 0.6208, 0.7568],
         [0.6013, 0.4189, 0.3824]],

        [[0.5329, 0.1500, 0.6710],
         [0.0660, 0.6279, 0.9239],
         [0.

In [ ]:
#do that laast part abt indexing

# *12. Indexing*

In [ ]:
import torch

test_12 = torch.randint(10, (5, 4))
test_12

tensor([[1, 6, 4, 7],
        [2, 3, 7, 8],
        [7, 4, 3, 0],
        [6, 1, 5, 4],
        [3, 1, 7, 8]])

In [ ]:
test_12[4]

tensor([3, 1, 7, 8])

In [ ]:
test_12[3][2]

tensor(5)

In [ ]:
test_122 = torch.randint(11, (2, 3, 3))
test_122

tensor([[[ 2,  9,  9],
         [ 1,  0,  7],
         [ 3,  9,  1]],

        [[10,  0,  1],
         [ 1,  7,  6],
         [ 6,  2,  3]]])

In [ ]:
test_122[0]

tensor([[2, 9, 9],
        [1, 0, 7],
        [3, 9, 1]])

In [ ]:
test_122[1][1][1]

tensor(7)

In [ ]:
test_122[:, 0]

tensor([[ 2,  9,  9],
        [10,  0,  1]])

In [ ]:
test_122[:, :, 2]

tensor([[9, 7, 1],
        [1, 6, 3]])

#*13. NumPy*

In [ ]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor #float 64 is not pytorch's default 32, bcs numpy default is 32; when converting between numpy and torch they will keep the dtypes respectfully

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor.dtype

torch.float64

In [ ]:
array.dtype

dtype('float64')

In [ ]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
tensor = tensor.type(torch.float32) #chaging the type

In [ ]:
tensor.dtype

torch.float32

In [ ]:
array = array + 1 #adding one to every element in the array, tensor stays the same (obvi)
array, tensor

(array([ 4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

# *14. Random Seed & Reproducibility*

In [ ]:
import torch

rand_tensor_A = torch.rand(3, 4)
rand_tensor_B = torch.rand(3, 4)

rand_tensor_A, rand_tensor_B, rand_tensor_A == rand_tensor_B

(tensor([[0.9093, 0.5141, 0.7166, 0.9322],
         [0.9303, 0.0916, 0.1910, 0.1956],
         [0.3947, 0.9703, 0.1000, 0.1328]]),
 tensor([[0.4737, 0.6664, 0.9383, 0.2810],
         [0.9017, 0.5817, 0.8431, 0.7943],
         [0.1709, 0.2163, 0.2687, 0.3516]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [ ]:
rand_tensor_C = torch.rand(2, 2)
rand_tensor_D = torch.rand(3, 3)

#rand_tensor_C == rand_tensor_D --> RESULTS IN ERROR

In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
rand_tensor_E = torch.rand(3, 3)

torch.manual_seed(RANDOM_SEED)
rand_tensor_F = torch.rand(3, 3)

rand_tensor_E, rand_tensor_F, rand_tensor_E == rand_tensor_F

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

-------------------------------------------
#*15. Putting stufff on GPU*

In [ ]:
!nvidia-smi

Sun Nov 19 16:38:53 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch

torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
tensor = torch.tensor([1, 2, 3])

tensor.device

device(type='cpu')

In [ ]:
tensor = tensor.to(device) #putting the tensor on GPU if available (check code above)
tensor.device

device(type='cuda', index=0)

In [ ]:
#tensor = tensor.to("cpu") #moving back to cpu
tensor = tensor.cpu() #or like this
tensor.device, tensor

(device(type='cpu'), tensor([1, 2, 3]))

In [ ]:
tensor = tensor.to(device) #back on gpu
#tensor.device

# tensor = tensor.numpy() --> results in error

tensor = tensor.cpu().numpy()
tensor

array([1, 2, 3])